# Interface binding
interface=wlan0ap
bind-interfaces

# --- DHCP Pool -----
dhcp-range=192.168.1.10,192.168.1.200,24h
# Gateway
dhcp-option=3,192.168.1.1
#  DNS Server
dhcp-option=6,192.168.1.1
# Broadcast Address
dhcp-option=28,192.168.1.255


#---- DNS ------
no-resolv
# For real queries to Google and Cloudfare
server=8.8.8.8
server=1.1.1.1

# Captive portal redirection 
# Resolve ALL domains to AP --> redirect to portal
address=//192.168.1.1 
# Uncomment the line above if you are running the captive portal on 192.168.1.1

# Logging
# Log every dhcp transaction
log-dhcp
log-facility=/var/log/dnsmasq-ap.log